title : Radio Stars 98.50 FM & DAB+ (BELGIUM)
description : Site de maintenance test
# url: http://RadioStarsBE.github.io/
timezone: Europe/Brussels
encoding: "utf-8"
lang: fr

theme: jekyll-theme-tactile # jekyll-theme-dinky
# plugins:
#   - jekyll-feed
markdown: kramdown
# paginate_path: 
# paginate: Nombre d'articles par page (pour la pagination).
# include: Liste des fichiers/dossiers à inclure même s'ils sont normalement ignorés.
# exclude: Liste des fichiers/dossiers à exclure du build.
